apiVersion: v1
kind: Service
metadata:
  name: fortis-frontend-service
  labels:
    app: fortis-bank
    tier: frontend
spec:
  type: NodePort
  selector:
    app: fortis-bank
    tier: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30800      # Access frontend at http://<ubuntu-vm-ip>:30800
